[package]
name = "unified_context"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-context = "0.1.1"
opentelemetry = { version = "0.25" }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
anyhow = "1"

[dev-dependencies]
opentelemetry = { version = "0.25" }
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3"
opentelemetry_sdk = { version = "0.25", features = ["rt-tokio"] }
opentelemetry-jaeger-propagator = { version = "0.25" }
opentelemetry-otlp = { version = "0.25", features = ["http-json"] }
tracing-opentelemetry = "0.26"
